---
language: go
go:
- 1.13.x
- tip
- 1.12.x
- 1.11.x
- 1.10.x
- 1.9.x
- 1.8.x
- "1.7"

env:
  global:
  - GO111MODULE=on

os:
- linux
- osx

sudo: false

go_import_path: github.com/dolmen-go/flagx

before_install:
- GO111MODULE=off go list ./... # Verify that go_import_path is ok for go < 1.11

install:
# Fetch dependencies:
# - go < 1.11:  go get -t -v ./...
# - go >= 1.11: go list -test -mod=readonly
- "case \"$(go version)\" in (*' go1.'[02-9]*|*' go1.10.'*) go get -t -v ./... ;; (*) go list -test -mod=readonly ./... ;; esac"

script:
# Test flagx with coverage for codecov.io
- go test -coverprofile=coverage.txt -covermode=atomic
# Test other modules without codecov.io
- find . -mindepth 2 -name 'go.mod' | sed 's/\/go.mod$//' | while read p; do (cd $p; go test ./...); done

after_success:
- bash <(curl -s https://codecov.io/bash)
